### ISSUE TITLE
Error in scroll function

### ISSUE THREAD

**Issue by Lucvolders** [bablokb/circuitpython-tm1637#1]
Hi I just stumbled upon an error in the scroll function.
The library says on line 209 ms-sleep but that is nor defined.
It should be time.sleep(delay)

Next the amount shoulod be a fraction of 1
for example .2 for 200 ms

Luc

**Comment by bablokb** [comment]
Yes, thanks. I missed this when I ported the library (and I haven't used this function myself).

**Comment by bablokb** [comment]
Fixed with b80cbb14690d49e40c2ebf8ca76f841452021da0
