### ISSUE TITLE
Memory error on Adafruit M0 Express

### ISSUE THREAD

**Issue by paulbaumgarten** [bablokb/circuitpython-tm1637#2]
Hello

Thanks for your driver! I'm trying to use it on an [Adafruit M0 Express board](https://www.adafruit.com/product/3505) and the bootloader has been upgraded to the current CircuitPython 6.3.0.

On trying the demo code I get a memory error. The serial console... 
```
Traceback (most recent call last):
  File "code.py", line 3, in <module>
MemoryError: memory allocation failed, allocating 187 bytes
```

I tried simplifying the example code somewhat but it's basically the same:
```python
import time
import board
import TM1637

if __name__ == "__main__":
  i = 0
  CLK = board.D8
  DIO = board.D9
  display = TM1637.TM1637(CLK, DIO)
  display.hex(0xbeef)
  time.sleep(5)
  while True:
    display.numbers(0 // 60,i % 60)
    time.sleep(1)
    i += 1
```

Any suggestions you have would be much appreciated.

**Comment by bablokb** [comment]
Strange, since I developed this with the Trinket M0 and that processor has basically the same specs. Maybe the newer version of the bootloader just takes up too much space. I will have to check this. You  could try to strip down the library and remove functions you don't need.

**Comment by paulbaumgarten** [comment]
Thanks for the quick response.

Your suggestion works. I deleted all the functions not required for `number()` and it came to life :) Cheers.
