### ISSUE TITLE
import subprocess?

### ISSUE THREAD

**Issue by xgpt** [bablokb/circuitpython-tm1637#3]
circuitpython yells at me when trying to import subprocess. how does one import subprocess? It appears to be a micropython thing.

**Comment by bablokb** [comment]
oh yes. It is in the sample main.py and not used at all, so indeed probably a leftover from a micropython example. The reason I did not notice it was that I developed this using Blinka, and Blinka uses the system python installation which does have a subprocess module.

So just remove it from main.py and try again. If it works, could you please report back? I will update the repo then.

**Comment by xgpt** [comment]
I believe it did but it was a while ago since I played with it I'm sorry!

**Comment by richpaul6806** [comment]
removing subprocess worked.

**Comment by bablokb** [comment]
Thanks. Fixed with https://github.com/bablokb/circuitpython-tm1637/commit/7255a68ed3448f6dd6423ae47192fef2718988ee
